### PR TITLE
Issue #18: Added ContentHandlerException

### PR DESCRIPTION
**Pull request by devcritter**
@rcrichton if you could please take a look?

We'll have to up to 3.0.0 since this is a breaking API change.

### CODE REVIEW

**Comment by devcritter** [comment]
@rcrichton actually put let's put the PR on hold. Just taking a look at the CDA handler's error handling and it's pretty comprehensive, allowing for a [collection](https://github.com/jembi/openmrs-module-shr-cdahandler/blob/master/api/src/main/java/org/openmrs/module/shr/cdahandler/exception/ValidationIssueCollection.java) of errors and warnings to be captured. Would be cool to try take advantage of that!

**Comment by devcritter** [comment]
@rcrichton think this is ready again for review. Basically just added a detail list to the exception. XDS.b error support lists of problems in the response, so I think this could work well with Justin's error collection.

**Comment by rcrichton** [comment]
Hey thanks Hannes this looks great. I just wonder if each detail item should be allowed to have an optional exceptions of its own. This may help with debugging. What do you think? Otherwise, :+1:

**Comment by devcritter** [comment]
@rcrichton yeah that's a cool idea. I added a ticket here #22. Although it shouldn't too much work, but we'd need to update the xds and cdahandler modules as well.

**Pull request merged**
